input.onButtonPressed(Button.A, function () {
    basic.showString("Hi")
    kBit.run(KBitDir.RunForward, 50)
    basic.pause(2100)
    kBit.carStop()
    kBit.motor(KBitMotorObs.RightSide, KBitMotorDir.Forward, 50)
    basic.pause(700)
    kBit.run(KBitDir.RunForward, 50)
    basic.pause(1800)
    kBit.carStop()
    kBit.motor(KBitMotorObs.LeftSide, KBitMotorDir.Forward, 50)
    basic.pause(700)
    kBit.run(KBitDir.RunForward, 50)
    basic.pause(2200)
    kBit.carStop()
    kBit.motor(KBitMotorObs.LeftSide, KBitMotorDir.Forward, 50)
    basic.pause(700)
    kBit.run(KBitDir.RunForward, 50)
    kBit.carStop()
    music.play(music.tonePlayable(262, music.beat(BeatFraction.Whole)), music.PlaybackMode.UntilDone)
})
